### ISSUE TITLE
Extract dump in PS3111 ROM Mode

### ISSUE THREAD

**Issue by brunohpg** [thesourcerer8/drresearch#18]
Is there any tool that can load the firmware into RAM so I can make a complete dump of the NAND?
I heard that there was a customized firmware on a Chinese forum, but I never found it.

My device is showing PS3111.

**Comment by DRCRecoveryData** [comment]
Dump without desolder not possible you need desolder using nand reader

**Comment by thesourcerer8** [comment]
I would recommend to ask around on forum.hddguru.com perhaps someone there knows a way.
