### ISSUE TITLE
How to use with Flash Extractor

### ISSUE THREAD

**Issue by DRCRecoveryData** [thesourcerer8/drresearch#8]
Hi,

I have dump nand via flash extractor, it's have chipinfo.txt and .dump files, could you update wiki for .dump files?

Also could you sent me your email i wanna share FE files to improve this project

**Comment by DRCRecoveryData** [comment]
1. i run: 
```C:\Users\Administrator\Downloads\Compressed\drresearch-main\drresearch-main>initpattern.exe 01_01.dump
Opened successfully
Image Size: -1 (0GB)
WARNING: The pattern required for a data size of 8192 is too large to fit into this device/image! Enlarge the image size to at least 47776 MB or change the pattern configuration
We have automatically adjusted the DATA size to 512 to fit into the device/image.
Creating old pattern for recovering the FTL
Creating new pattern for recovering XOR and LDPC
We are done writing the pattern.
The configuration has been written to pattern.xml please provide this file too in the end.
Please wait a couple of seconds to make sure everything has been written, then eject the drive properly.
Then connect the NAND flash and dump it.```

and get this file:

[pattern.zip](https://github.com/thesourcerer8/drresearch/files/13485681/pattern.zip)

how it's next step?

**Comment by thesourcerer8** [comment]
If you use the initpattern tool to write an image, you have to add the image size you want, like e.g.
initpattern.exe 01_01.dump 64GB
Without an image size, it will just create an empty dump file.
I would suggest to write the pattern to a disk directly, please watch these videos where the usage of the initpattern tool it is demonstrated:
https://www.youtube.com/watch?v=rRWWPTnJn4U
https://www.youtube.com/watch?v=z93vdLnfoDs

**Comment by thesourcerer8** [comment]
I have improved the warnings and errors of the initpattern tool for these situations now.
I have added FE Chip.txt support for the casefiles, so you can use Chip.txt files as casefiles now.
